version: '2'

services:
  ci-build:
    image: microsoft/dotnet:1.1-sdk
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c 'dotnet restore && dotnet pack -c Release -o "$$(pwd)/artifacts"'
